### ISSUE TITLE
Implement writer in C++

### ISSUE THREAD

**Issue by paulmueller** [ZELLMECHANIK-DRESDEN/rtdc_hdf5#1]
reference: https://support.hdfgroup.org/HDF5/Tutor/rdwt.html

**Comment by phidahl** [comment]
The writer is running and being tested at the moment.
Regarding the format there are a few points that we might need to change:

1. Creating a new dataset for each contour is causing too much overhead. It reduces possible rates for writing. For larger datasets (> 100,000 events) opening of the files takes very long, if there is a dataset for each contour.
2. Attributes: I tested my datasets with dclab-verfiy. I got errors because of missing attributes. But those were also not contained in files created with the tdsm2hdf5 converter...
I think it would be better not to call a dataset invalid if it contains additional attributes that are (not yet) known to dclab. We should keep the option open to add more attributes in the future, while keeping compatibility.

As a solution to point 1. I would suggest to write binary images of the contour. They would be about 30kBytes per image if encoded in 8bit. I'm going to find out if it is possible to write 8 pixels per byte which would be much more efficient.

**Comment by paulmueller** [comment]
Thanks for the update!

1. Ok, but several things in dclab rely on the contour being a (N,2) array. So we would need to have a reliable converter between binary and contour coordinates. Regarding the 8 pixels per byte, is it not possible to store a boolean array with hdf5? Keep in mind that data retrieval with h5py should be intuitive.

2. No, I want to be as strict as possible here to avoid trouble in the future (as we are having with the various tdms file formats). dclab-verify should give absolutely no error for all **new** .rtdc data sets. This ensures quality and enforces the rtdc data file format specification. Regarding the tdsm2rtdc converter: This is a convenience method and the files produced should not be taken as a quality reference. If we want to add new attributes to the rtdc data files, we should add them to dclab first. Backwards compatibility can always be ensured that way. And I know what is going on as well.

**Comment by paulmueller** [comment]
1. Very good. Compression is probably the best way to go.

2. Currently I think, fluorescence related parameters are only checked if there actually is fluorescence data, so this case might already be covered. Please create a separate issue in dclab and we can talk about it. I am also planning to make dclab-verify-dataset more user-friendly such that you kind of get a summary of what is missing, what should be there, and what does not make any sense.

3. Log files are stored as variable datasets with variable-length h5 strings. Each index in the dataset corresponds to one line in the log file. https://github.com/ZELLMECHANIK-DRESDEN/dclab/blob/master/dclab/rtdc_dataset/write_hdf5.py#L282-L288
