### ISSUE TITLE
hdf5 metadata key names

### ISSUE THREAD

**Issue by paulmueller** [ZELLMECHANIK-DRESDEN/rtdc_hdf5#9]
TODO:
- [x] create a list of default metadata key names (with units?) (The current metadata key names are inconsistent)
- [x] sort metadata keys according to: setup / sample / environment / ...?

**Comment by paulmueller** [comment]
Here is a proposal for the configuration keywords that should be supported by the .rtdc file format:
https://github.com/ZELLMECHANIK-DRESDEN/rtdc_hdf5/blob/master/Python/configuration.py

I have renamed a few variables from the tdms-.ini files and added a few new parameters. They are now sorted in what I believe is a consistent way.

@phidahl: There are a few things that still need to be addressed and that I need your help with:
- Please verify that the unit of every parameter is correct
- The list is most-likely incomplete. Please check if we should add other keywords
- Do you agree with the sorting of the keywords?
- I think we can remove these keywords (with exemplary values):
    - `FLUOR - Format = int16`
    - `Image - Cell Min = 10.000000`
    - `Image - Cell Max = 50`
- I do not know what these keywords do. Maybe you could help me out with an explanation, if we are using them.
    -`Image - t1 = -256`
    -`Image - t2 = -6`
    -`FLUOR - ADCmin = -1`
    -`FLUOR - ADCmax = 1`
    -`Framerate - Tap Code`
    -`Framerate - Tap Mode`

**Comment by phidahl** [comment]
@paulmueller, I think the list is almost complete.

The order is fine. Is the parser working in a way that the sorting does matter? - In the end we are going to put this into the hdf5 file, right?

I checked the units:
The bounding box sizes have a unit of µm not pix. (size_px_x max etc.)

- FLUOR - Format will be replaced with FLUOR - bit depth
- Image - Cell Min / Max can be removed

- Image - t1 is a parameter of the thresholding. But will be obsolete soon. Can be removed.
- Image - t2 is the threshold (because of the FPGA framegrabber program, the value needed to be negative... ) But this will be obsolete, too.
- FLUOR - ADCmin/max define the range of the fluorescence signal acquisition in Volt. Pleas keep.
- Framerate - Tap Code and Mode say something about the camera connection. can be deleted.

It would be good if we could also store a log of the measurement for debugging. Is it possible in hdf5 to have something like a text file? - Here diagnostic information would be stored.

**Comment by paulmueller** [comment]
Ok, I updated https://github.com/ZELLMECHANIK-DRESDEN/rtdc_hdf5/blob/master/Python/meta.py.

The sorting does not matter. Yes, these meta data will be put in "/meta/" of the hdf5 file. The column and image, etc. data will be stored in "/data/". Log files could be stored in "/log/" as datasets containing Variable-length UTF-8 strings. I updated #2.

**Comment by paulmueller** [comment]
Thanks, I am closing this now.
